name: Elixir Core CD/CI

on:
  push:
    branches: [ "*" ]  # changed from "*" to "main" for specificity
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Install Elixir Runtime
      uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21 # v1.16.0
      with:
        elixir-version: '1.15.7' # [Required] Define the Elixir version
        otp-version: '26.1.2'    # [Required] Define the Erlang/OTP version     
    - name: Restore deps From Cache
      uses: actions/cache@v3
      with:
        path: ./deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Restore _build From Cache
      uses: actions/cache@v3
      with:
        path: |
          ./_build
          ./priv/plts 
        key: test-${{ runner.os }}-build-${{ hashFiles('**/mix.lock') }}
        restore-keys: test-${{ runner.os }}-build-
    - name: Purge proj specific build artifacts
      run: |
        rm -rf ./_build/test/rel
        rm -rf ./_build/test/lib/noizu_labs_open_ai
    - name: Test Suite
      run: |
        mix deps.get
        mix test --cover
    - name: Linter
      run: |
        mix dialyzer --format github --ignore-exit-status
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          ./_build/test/lib/noizu_labs_open_ai/results.xml
    - name: Purge specific build artifacts
      run: |
        rm -rf ./noizu_labs_open_ai/_build/test/rel
        rm -rf ./noizu_labs_open_ai/_build/test/lib/noizu_labs_open_ai
